- name: configure the backend server
  hosts: backend
  become: yes
  tasks:
    - name: disable default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enable nodejs
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: install
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: create expense user
      ansible.builtin.user:
        name: expense

    - name: create app directory
      ansible.builtin.file:
        name: /app
        state: directory

    - name: download the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip

    - name: extract files
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
