- name: frontend configuration
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: remove the html content
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent
