- name: frontend configuration
  hosts: frontend
  become: yes
  tasks:
    - name: install nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start nginx
      ansible.builtin.package:
        name: nginx
        state: started
        enabled: yes

    - name: remove the defualt content
      ansible.builtin.command: rm -rf /usr/share/nginx/html/*
